### ISSUE TITLE
Is this data the same as the Hobbit Strategy Battle Game?

### ISSUE THREAD

**Issue by OftKilted** [BSData/war-of-the-ring#1]
There is currently a (slightly disused) repository for the Hobbit Battle Strategy Battle Game.

What is the difference between this repository and the prior? Is this for a newer or older version? Can the older Hobbit data files be removed/retired/depreciated?

**Comment by Dr-Csernus** [comment]
No, Hobbit SBG is the skirmish version of the Lord of the Rings game, War of the Ring is the movement tray version.
